### ISSUE TITLE
New cookie message pattern

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-brochure-theme#48]
The pattern would be an adaptation of the existing Vanilla [notifications](https://docs.vanillaframework.io/en/patterns/notification) pattern. The design can be seen at the bottom of this [thread](https://github.com/ubuntudesign/vanilla-brochure-theme-design/issues/9#issuecomment-284393654).

**Comment by nottrobin** [comment]
Leaving this open for now, pending further discussion about how to display the cookie notification.

**Comment by anthonydillon** [comment]
I would like to note that the design is great and the context of the
continued discussion should be about moving the cookie policy notification
to the footer instead on a visible banner.

**Comment by anthonydillon** [comment]
@yaili to talk to @pmahnke about this.

**Comment by yaili** [comment]
@anthonydillon this is closed, right?

**Comment by anthonydillon** [comment]
Yes please
