### ISSUE TITLE
Have 3 distinct types of vertical padding in strips

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-brochure-theme#51]
There was an [issue on the brochure theme](https://github.com/vanilla-framework/vanilla-brochure-theme/issues/13) repo to add a strip hero variation with more vertical padding, but after [investigation](https://github.com/vanilla-framework/vanilla-brochure-theme/issues/13#issuecomment-283968773) it turns out we use mainly two types of vertical and neither is exclusive to hero rows.

The proposal is that we have two options for vertical padding in strips in the brochure theme:

- 60px - "shallow"
- 100px - "deep"

**Comment by yaili** [comment]
- 40px is "shallow"
- 60px is default
- 100px is "deep"

**Comment by yaili** [comment]
Was this not accepted? @anthonydillon

**Comment by barrymcgee** [comment]
It was - updating labels..

**Comment by yaili** [comment]
@anthonydillon @barrymcgee was this done?

**Comment by anthonydillon** [comment]
No, not yet if it's ready it should be triaged. Could you update the spec so we capture small screen sizes and any other aspects of the modifier, please?

**Comment by yaili** [comment]
OK 

Ref https://github.com/ubuntudesign/vanilla-brochure-theme-design/issues/15

**Comment by yaili** [comment]
Spec: https://github.com/ubuntudesign/vanilla-brochure-theme-design/tree/master/Strip

**Comment by yaili** [comment]
I tried to keep the spacing to the variables, and/or multiples of 8
