### ISSUE TITLE
Heading icon not implemented according to spec

### ISSUE THREAD

**Issue by yaili** [vanilla-framework/vanilla-brochure-theme#78]
If you see an example of heading icon on ubuntu.com ([demo](http://www.ubuntu.com-1625-download-desktop.demo.haus/download/desktop) - scroll down to "Get the version you need") the icon is not aligned top with the heading. This is more evident if you reduce the screen size to about 880px wide, when 2 titles go over 2 lines, and one over 3 lines. This is less evident in the example above ("Easy ways to switch to Ubuntu").

Also, this pattern shouldn't determine the font-size or line-height of the heading.

Spec: https://github.com/ubuntudesign/vanilla-brochure-theme-design/tree/master/Heading%20icon

<img width="883" alt="screen shot 2017-05-19 at 16 13 41" src="https://cloud.githubusercontent.com/assets/223966/26254348/25ddf09c-3cae-11e7-9273-a53a03cfd3e1.png">

**Comment by yaili** [comment]
@grahambancroft would be good to fix this one next

**Comment by pmahnke** [comment]
I put a temp fix in style-v1 for this

```css
.p-heading-icon__img {
  align-self: flex-start;
}
```
